%YAML:1.0
annotators:
    - CollectionReader
    - ImagePreprocessor
    - PointCloudFilter
    - NormalEstimator
    - PlaneAnnotator
    - PointCloudClusterExtractor
    - ColorClusterer
    - PointCloudColorSegmentation
    - PrimitiveShapeAnnotator
    - PlateAnnotator
    - SpatulAnnotator
    - CakeAnnotator
    - BoardAnnotator
    - KnifeAnnotator
    - ROSPublisher
