%YAML:1.0
annotators:
    - CollectionReader
    - ImagePreprocessor
    - RegionFilter
    - SzeneRecorder
    - NormalEstimator
    - PlaneAnnotator
    - PointCloudClusterExtractor
    - ColorClusterer
    - TrayAnnotator
    - CakeAnnotator
    - KnifeAnnotator
    - ROSPublisher
