%YAML:1.0
annotators:
    - CollectionReader
    - ImagePreprocessor
    - ObjectRegionFilter
    - NormalEstimator
    - PlaneAnnotator
    - PointCloudClusterExtractor
    - ColorClusterer
    - KnifeAnnotator
    - ROSPublisher
