%YAML:1.0
annotators:
    - CollectionReader
    - ImagePreprocessor
    - PointCloudFilter
    - NormalEstimator
    - PlaneAnnotator
    - PointCloudColorSegmentation
    - PrimitiveShapeAnnotator
    - PlateAnnotator
    - ROSPublisher
