%YAML:1.0
annotators:
    - CollectionReader
    - ImagePreprocessor
    - RegionFilter
    - NormalEstimator
    - PlaneAnnotator
    - PointCloudClusterExtractor
    - SpatulAnnotator
    - ROSPublisher
